analyzer:
  errors:
    must_be_immutable: ignore
    inference_failure_on_instance_creation: ignore 
    lines_longer_than_80_chars: ignore
    use_build_context_synchronously: ignore
    document_ignores: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false